// <auto-generated />
using Angel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angel.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190730052103_SeedDataandDeletedImageProp")]
    partial class SeedDataandDeletedImageProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Angel.Model.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CollectionName");

                    b.Property<string>("Description");

                    b.Property<int>("ManufacturerId");

                    b.HasKey("CollectionId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Collections");

                    b.HasData(
                        new { CollectionId = 1, CollectionName = "Classic", Description = "The Rolex Classic collection consists of models that combines Rolex’s know-how and high standards of perfection in an approach that heightens watchmaking heritage in its most timeless form.", ManufacturerId = 1 },
                        new { CollectionId = 2, CollectionName = "Sea Master", Description = "In 1970 OMEGA officially launched a watch that had been created to withstand the crushing pressures endured by divers working deep below the ocean’s surface. It was the Seamaster ", ManufacturerId = 2 }
                    );
                });

            modelBuilder.Entity("Angel.Model.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new { ManufacturerId = 1, Country = "Swiss", Description = "Rolex SA is a Swiss luxury watch manufacturer based in Geneva, Switzerland. Originally founded as Wilsdorf and Davis by Hans Wilsdorf and Alfred Davis in London, England in 1905, the company registered Rolex as the brand name of its watches in 1908 and became Rolex Watch Co. Ltd. in 1915.", ImageURL = "https://upload.wikimedia.org/wikipedia/en/9/95/Rolex_logo.svg", Name = "Rolex" },
                        new { ManufacturerId = 2, Country = "Swiss", Description = "Omega SA is a Swiss luxury watchmaker based in Biel/Bienne, Switzerland. Founded by Louis Brandt in La Chaux-de-Fonds in 1848, the company formally operated as the La Generale Watch Co. until incorporating the name Omega in 1903, becoming Louis Brandt et Frère - Omega Watch & Co.", ImageURL = "https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwilvpuK79vjAhVJDq0KHW1iD5QQjRx6BAgBEAU&url=http%3A%2F%2Flogok.org%2Fomega-logo%2F&psig=AOvVaw3-48uIkp6C4cUFSgLfGQfX&ust=1564549445969194", Name = "Omega SA" }
                    );
                });

            modelBuilder.Entity("Angel.Model.Watch", b =>
                {
                    b.Property<int>("WatchId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollectionId");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Movement");

                    b.Property<string>("Name");

                    b.HasKey("WatchId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Watches");

                    b.HasData(
                        new { WatchId = 1, CollectionId = 1, ImageURL = "https://www.rolex.com/watches/pearlmaster/m86285-0001.html#", Movement = "3701", Name = "PearlMaster 39" },
                        new { WatchId = 2, CollectionId = 2, ImageURL = "https://www.omegawatches.com/en-us/watch-omega-seamaster-ploprof-1200m-omega-co-axial-55-x-48-mm-22432552101002", Movement = "55 X 48 MM", Name = "Ploprof" }
                    );
                });

            modelBuilder.Entity("Angel.Model.Collection", b =>
                {
                    b.HasOne("Angel.Model.Manufacturer")
                        .WithMany("Collections")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angel.Model.Watch", b =>
                {
                    b.HasOne("Angel.Model.Collection")
                        .WithMany("Watches")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
